name: Daily Commit

on:
  schedule:
    - cron: '30 10 * * *'   # daily at 10:30 UTC
  workflow_dispatch:        # allows manual run for testing

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit daily update - 25ds1000098@ds.study.iitm.ac.in
        run: |
          FILE=daily_update.txt
          # Add current timestamp to the file to ensure changes
          echo "$(date)" > $FILE
          git config --global user.name "GitHub Actions"
          git config --global user.email "25ds1000098@ds.study.iitm.ac.in"
          git add $FILE
          git commit -m "Daily update $(date)"
          git push
